Script started on 2022-02-11 15:06:00-05:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="121" LINES="37"]
]0;hs59@gold12: ~/cs214/lab/05[01;32mhs59@gold12[00m:[01;34m~/cs214/lab/05[00m$ s clojure
[KClojure 1.10.1
[Kuser=> [Kuser=> [Kuser=> (defn s S sque areSuare    quare[1P squareSquare(fn [x][x] (* x 9 9 (* x)(* x))(* x (* x)))(fn [x] (* x (* x))))user=> (def squareSquare(fn [x] (* x (* x))))* [1@ [1@x [1P[1@x [1@ [1@x [1@ [1@x [1@ [1@x ([1P*[1P[1P[1P[1P[1P[1P))))   )(fn [x] (* x x x x)))user=> (def squareSquare(fn [x] (* x x x x)))user=> [K(def squareSquare(fn [x] (* x x x x)))
[K#'user/squareSquare
user=> [Kuser=> [Kuser=> s squareSquare 225)[1@(squareSquare 225)user=> [K(squareSquare 225)
2562890625
user=> [Kuser=> [Kuser=> (squareSquare 225)[1P)[1P)[1P)1)5)user=> [K(squareSquare 15)
50625
user=> [Kuser=> [Kuser=> (squareSquare 15)5[1P)[1P)2)user=> [K(squareSquare 2)
16
user=> [Kuser=> [Kuser=> (squareSquare 2)[1P)3)user=> [K(squareSquare 3)
81
user=> [Kuser=> [Kuser=> 
[K]0;hs59@gold12: ~/cs214/lab/05[01;32mhs59@gold12[00m:[01;34m~/cs214/lab/05[00m$ exit

Script done on 2022-02-11 15:11:37-05:00 [COMMAND_EXIT_CODE="0"]
